CREATE DATABASE IF NOT EXISTS capybara_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE capybara_db;

CREATE TABLE IF NOT EXISTS faith_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  guild_id VARCHAR(32) NOT NULL,
  discord_id VARCHAR(32) NOT NULL,
  faith_level INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_guild_user (guild_id, discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
